name: ff_boost_panel
description: "Professional Gaming GFX and Boost Tool"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
<<<<<<< HEAD
  installed_apps: ^1.4.3
  device_info_plus: ^10.1.0 
=======
  device_apps: ^2.2.0
  device_info_plus: ^10.1.0
  
>>>>>>> cb2777a0bcd4722e79e8811bb1b2cd2b188716d3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
